version: "3.9"
services:
  local-mmoai:
    build:
      context: .
      dockerfile: Dockerfile.local
    restart: always
    command: ["tail", "-f", "/dev/null"]
    environment:
      - MONGODB_HOST=local-mongodb
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=root
    volumes:
      - ./mmoai:/root/mmoai
    depends_on:
      local-mongodb:
        condition: service_healthy


  local-mongodb:
    image: mongodb/mongodb-enterprise-server:7.0.5-ubi8
    restart: always
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: root
    command: [
      "mongod",
      "--bind_ip_all",
      "--wiredTigerCacheSizeGB=1"
    ]
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1'
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
