version: "3.9"
services:
  local-mmoai:
    build:
      context: .
      dockerfile: Dockerfile.local
    restart: always
    command: []
    environment:
      - MONGODB_HOST=local-mongodb

    volumes:
      - ./mmoai:/root/mmoai

    depends_on:
      - local-mongodb

    links:
      - local-mongodb

  local-mongodb:
    image: mongo:7.0.9
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

    ports:
      - "27017:27017"